version: '3'
services:
     db:
        image: postgres:14.8
        user: root
        environment:
          - POSTGRES_USER=odoo
          - POSTGRES_PASSWORD=odoo
          - POSTGRES_DB=postgres
        volumes:
          - ../ecare16ce-odoo--db-data-dir:/var/lib/postgresql/data
     web:
       build:
         context: .
         dockerfile: Dockerfile
       user: odoo
       ports:
       - "8069:8069"
       depends_on:
         - db
#       volumes:
#         - ../ecare16ce-odoo-data-dir:/var/lib/odoo