version: '3'
services:
     db:
        container_name: icsi_odoo16ce_db
        image: postgres:14.8
        user: root
        environment:
          - POSTGRES_USER=odoo
          - POSTGRES_PASSWORD=odoo
          - POSTGRES_DB=postgres
        volumes:
          - odoo16ce_db:/var/lib/postgresql/data
        ports:
          - "5433:5432"
     web:
       container_name: icsi_odoo16ce_web
       build:
         context: .
         dockerfile: Dockerfile
       user: odoo
       ports:
       - "8076:8069"
       depends_on:
         - db
       links:
         - db
       volumes:
         - icsi_odoo16ce_config:/etc/odoo:rw
         - icsi_odoo16ce_data_dir:/opt/odoo/data_dir

volumes:
  icsi_odoo16ce_data_dir:
    external: true
  odoo16ce_db:
    external: true
  icsi_odoo16ce_config:
    external: true
