version: '3'
services:
     db:
        container_name: odoo16ce_staging_db
        image: postgres:14.8
        user: root
        environment:
          - POSTGRES_USER=odoo
          - POSTGRES_PASSWORD=odoo
          - POSTGRES_DB=postgres
        volumes:
          - odoo16ce_staging_odoo16ce_db:/var/lib/postgresql/data
#          - tt_prod_odoo16ce_db:/etc/postgresql/14/main
#          - /opt/tt-erp/volume/datadir_postgres:/etc/postgresql/14/main
        ports:
          - "5433:5432"
     web:
       container_name: odoo16ce_staging
       build:
         context: .
         dockerfile: Dockerfile
       user: odoo
       ports:
       - "8075:8069"
#       deploy:
#         mode: replicated
#         replicas: 3
       depends_on:
         - db
       links:
         - db
       volumes:
         - odoo-config:/etc/odoo:rw
         - odoo16ce_staging_odoo16ce_data_dir:/opt/odoo/data_dir
#         - /opt/tt-erp/volume/odoo16ce_tt_prod/extra-addons:/mnt/extra-addons

volumes:
  odoo16ce_staging_odoo16ce_data_dir:
    external: true
  odoo16ce_staging_odoo16ce_db:
    external: true
  odoo-config:
    external: true
