from . import patient
from . import individual_patient
from . import general_history
from . import female_obstetrics_history
from . import female_gynaecological_history
from . import first_consultation
from . import social_history
from . import lab_history
from . import genital_examination
