from odoo import api, models, fields, _
from odoo.addons.ecare_medical_history.utils.static_members import StaticMember


class MedicalHistory(models.Model):
    _name = "ec.medical.history"
    _description = "Medical History"

    consultation_id = fields.Many2one(comodel_name='ec.first.consultation', string='First Consultation')

    # Female-specific fields with the 'female_' prefix
    female_adrenal_pr = fields.Char('Adrenal')
    female_ant_pr = fields.Selection([('Yes', 'Yes'), ('No', 'No')], string='Anti-phospholipid Syndrome')
    female_aut_pr = fields.Char('Autoimmune Diseases')
    female_car_pr = fields.Char('Cardiac')
    female_gal_pr = fields.Char('Gall Bladder')
    female_gas_pr = fields.Char('Gastric')
    female_gyn_pr = fields.Char('Gynaecological')
    female_hae_pr = fields.Char('Haematological')
    female_int_pr = fields.Char('Intestinal')
    female_liver_pr = fields.Char('Liver')
    female_low_pr = fields.Char('Lower Urinary Tract')
    female_mal_pr = fields.Char('Malignancies Pr')
    female_neu_pr = fields.Char('Neurological')
    female_renal_pr = fields.Char('Renal')
    female_res_pr = fields.Char('Respiratory')
    female_ske_pr = fields.Char('Skeletal')
    female_thy_pr = fields.Text('Thyroid Pr')
    female_thy_select_pr = fields.Selection([('Hypothyroidism', 'Hypothyroidism'), ('Hyperthyroidism', 'Hyperthyroidism')], 'Thyroid')
    female_hdisease_pr = fields.Char(string='Heart Disease')
    female_uinfact_pr = fields.Char(string='Urinary Infections')
    female_htension_pr = fields.Char(string='Hypertension Pr')
    female_allergies_pr = fields.Text(string='Allergies Pr')
    female_btransfusion_pr = fields.Selection(selection=[('Yes', 'Yes'), ('No', 'No')], string='Blood Transfusion')
    female_janduice_pr = fields.Char(string='Jaundice')
    female_complications_pr = fields.Text(string='Complications')
    female_diabetes_pr = fields.Text(string='Diabetes Pr')
    female_diabetes_select_pr = fields.Selection(selection=[('IDDM', 'IDDM or type 1'), ('NIDDM', 'NIDDM or type 2')], string='Diabetes')
    female_dvt_pr = fields.Char(string='DVT')
    female_saa_pr = fields.Char(string='Smoking')
    female_alcohol_pr = fields.Char(string='Alcohol')
    female_alcohol_pr_d = fields.Date(string='Alcohol Date')
    female_operations_pr = fields.Text(string='Operations (if any)')
    female_others_pr = fields.Char(string='Others')

    # Dates relevant to fields
    female_adrenal_pr_d = fields.Date('Adrenal Date')
    female_allergies_pr_d = fields.Date('Allergies Date')
    female_ant_pr_d = fields.Date('Anti-phospholipid Syndrome Date')
    female_aut_pr_d = fields.Date('Autoimmune Diseases Date')
    female_btransfusion_pr_d = fields.Date('Blood Transfusion Date')
    female_car_pr_d = fields.Date('Cardiac Date')
    female_diabetes_pr_d = fields.Date('Diabetes Date')
    female_dvt_pr_d = fields.Date('DVT Date')
    female_gal_pr_d = fields.Date('Gall Bladder Date')
    female_gas_pr_d = fields.Date('Gastric Date')
    female_gyn_pr_d = fields.Date('Gynaecological Date')
    female_hae_pr_d = fields.Date('Haematological Date')
    female_hdisease_pr_d = fields.Date('Heart Disease Date')
    female_htension_pr_d = fields.Date('Hypertension Date')
    female_int_pr_d = fields.Date('Intestinal Date')
    female_janduice_pr_d = fields.Date('Jaundice Date')
    female_liver_pr_d = fields.Date('Liver Date')
    female_low_pr_d = fields.Date('Lower Urinary Tract Date')
    female_mal_pr_d = fields.Date('Malignancies Date')
    female_neu_pr_d = fields.Date('Neurological Date')
    female_renal_pr_d = fields.Date('Renal Date')
    female_res_pr_d = fields.Date('Respiratory Date')
    female_saa_pr_d = fields.Date('Smoking Date')
    female_ske_pr_d = fields.Date('Skeletal Date')
    female_thy_pr_d = fields.Date('Thyroid Date')
    female_uinfact_pr_d = fields.Date('Urinary Infections Date')
    female_operations_pr_d = fields.Date('Operations Date')
    female_others_pr_d = fields.Date('Others Date')
